export const ClothesData = [
  {
    marque: "H&m",
    title: "Short Black Dress",
    description:
      "Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.",
    actualPrice: "19.99$",
    oldPrice: "25$",
    quantityRated: 10,
    imageLittle: "https://i.postimg.cc/x8HyP5L7/black-dress.png",
    imageBig: "https://i.postimg.cc/KcTxSTf8/black-dress-big-Size.png",
    imageBigV2:
      "https://i.postimg.cc/SQcFthQX/black-dress-big-Size-profile.png",
    color: "black",
    size: ["XS", "S", "M", "L", "XL"],
  },
  {
    marque: "Mango",
    title: "T-Shirt SPANISH",
    description:
      "Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.",
    actualPrice: "9$",
    oldPrice: "19$",
    quantityRated: 3,
    imageLittle: "https://i.postimg.cc/4NDQnDRg/t-shirt-spanish.png",
    imageBig: "https://i.postimg.cc/L60Ttqdj/t-shirt-spanish-big-Size.png",
    imageBigV2: "https://i.postimg.cc/L60Ttqdj/t-shirt-spanish-big-Size.png",
    color: "white",
    size: ["XS", "S", "M", "L", "XL"],
  },
  {
    marque: "Mango",
    title: "Pullover",
    description:
      "Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.",
    actualPrice: "51$",
    oldPrice: "",
    quantityRated: 13,
    imageLittle: "https://i.postimg.cc/rpFjLSL0/pullover.png",
    imageBig: "https://i.postimg.cc/MZYM2gdT/pullover-big-Size.png",
    imageBigV2: "https://i.postimg.cc/MZYM2gdT/pullover-big-Size.png",
    color: "gray",
    size: ["XS", "S", "M", "L", "XL"],
  },
  {
    marque: "Mango",
    title: "Pullover",
    description:
      "Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.",
    actualPrice: "51$",
    oldPrice: "",
    quantityRated: 13,
    imageLittle: "https://i.postimg.cc/xdxRjc0s/pullover-blue.png",
    imageBig: "https://i.postimg.cc/hGw8m6Hg/pullover-blue-big-Size.png",
    imageBigV2: "https://i.postimg.cc/hGw8m6Hg/pullover-blue-big-Size.png",
    color: "blue",
    size: ["XS", "S", "M", "L", "XL"],
  },
  {
    marque: "Dorothy Perkins",
    title: "Evening Dress",
    description:
      "Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.",
    actualPrice: "32$",
    oldPrice: "",
    quantityRated: 0,
    imageLittle: "https://i.postimg.cc/s224Lf2S/dress.png",
    imageBig: "https://i.postimg.cc/hGw8m6Hg/pullover-blue-big-Size.png",
    imageBigV2: "https://i.postimg.cc/hGw8m6Hg/pullover-blue-big-Size.png",
    color: "blue",
    size: ["XS", "S", "M", "L", "XL"],
  },
  {
    marque: "Dorothy Perkins",
    title: "Blouse",
    description:
      "Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.",
    actualPrice: "14$",
    oldPrice: "21$",
    quantityRated: 13,
    imageLittle: "https://i.postimg.cc/VLQFNy8c/blouse.png",
    imageBig: "https://i.postimg.cc/1XZNyQNC/blouse-BIGs-IZE.png",
    imageBigV2: "https://i.postimg.cc/1XZNyQNC/blouse-BIGs-IZE.png",
    color: "white",
    size: ["XS", "S", "M", "L", "XL"],
  },
  {
    marque: "Dorothy Perkins",
    title: "Veste",
    description:
      "Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.",
    actualPrice: "32$",
    oldPrice: "",
    quantityRated: 10,
    imageLittle: "https://i.postimg.cc/vDFXRkQb/veste.png",
    imageBig: "https://i.postimg.cc/W43y7RzH/veste-big-Size.png",
    imageBigV2: "https://i.postimg.cc/W43y7RzH/veste-big-Size.png",
    color: "blue",
    size: ["XS", "S", "M", "L", "XL"],
  },
  {
    marque: "Dorothy Perkins",
    title: "Pull",
    description:
      "Short dress in soft cotton jersey with decorative buttons down the front and a wide, frill-trimmed square neckline with concealed elastication. Elasticated seam under the bust and short puff sleeves with a small frill trim.",
    actualPrice: "22$",
    oldPrice: "",
    quantityRated: 8,
    imageLittle: "https://i.postimg.cc/63xdpRkf/pull.png",
    imageBig: "https://i.postimg.cc/tRSYrWBv/pull-big-Size.png",
    imageBigV2: "https://i.postimg.cc/tRSYrWBv/pull-big-Size.png",
    color: "blue",
    size: ["XS", "S", "M", "L", "XL"],
  },
];
 